server:
  port: 8048
spring:
  application:
    name: mail-order-pharmacy
  cloud:
    gateway:
      routes:
      - id: auth-service
        predicates:
        - Path=/authapp/**
        uri: http://localhost:8090/
      - id:
        - drug-service
        predicates:
        - - Path=drugdetailapp/**
        uri:
        - http://localhost:8081/

